version: "3.8"

services:
   ## Database Service
   database: 
    image: mysql:8.0
    ports:
        - 3306:3306
    environment:
        - MYSQL_DATABASE  = ${DB_DATABASE}
        - MYSQL_USERANAME = ${DB_USERANAME}
        - MYSQL_PASSWORD  = ${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD  = ${DB_PASSWORD}
    volumes:
        - db-data:/var/lib/mysql